DefaultContentLanguage = "en"
author = "Swarnim Shashank"
baseURL = 'https://quasinormalguy.github.io/'
#copyright = "Copyright © 2022"
copyright = ""
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
hasCJKLanguage = true
languageCode = "cn"
theme = 'hugo-theme-tokiwa'
#title = 'Just a (quasi) normal guy'
title = "金月"

[markup]
[markup.highlight]
style = "monokailight"

[markup.goldmark.renderer]
unsafe = true

[params]
#bannerFont = "fonts/mononoki"
bannerFont = "/fonts/杨任东竹石体-Regular"

description = """
### Hello! I am Swarnim.
I am a postdoc who writes codes to solve problems related to relativistic astrophysics. I work in the group of [Prof. Cosimo Bambi](https://cosimobambi.github.io) at Fudan University, Shanghai.  
This is my personal website.
<br/><br/>
![BH disk](/img/bh-disk.jpg)
""" #नमस्ते!\\

favicon = "/img/thinker.png" 
fuse = true # for searchbox. "JSON" must added to output contents. See [outputs].
math = true # for introducing $KaTEX$
useChineseFonts = true 
postDateFormat = "2006-1-2"

[menu]
# Shown in the side menu.

[[menu.main]]
identifier = "research"
name = "My Research"
url = "/research/"
weight = 1

[[menu.main]]
identifier = "about"
name = "About Me"
url = "/about/"
weight = 2

[[menu.main]]
identifier = "vita"
name = "CV"
url = "/vita/"
weight = 3

#[[menu.main]]
#identifier = "post"
#name = "blog"
#url = "/post/"
#weight = 4

[social]
github = "http://github.com/quasinormalguy"
mail = "mailto:swarnim@tuta.io"
#twitter = "http://twitter.com/quasinormalguy"

[outputs]
home = ["HTML", "JSON"]
